/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('./google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.WSMessage', null, global);
goog.exportSymbol('proto.WSMessage.MsgType', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.WSMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.WSMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.WSMessage.displayName = 'proto.WSMessage';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.WSMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.WSMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.WSMessage} msg The msg instance to transform.
 * @return {!Object}
 */
proto.WSMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    mid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    type: jspb.Message.getFieldWithDefault(msg, 2, 0),
    uid: jspb.Message.getFieldWithDefault(msg, 3, ""),
    tId: jspb.Message.getFieldWithDefault(msg, 4, ""),
    txt: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.WSMessage}
 */
proto.WSMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.WSMessage;
  return proto.WSMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.WSMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.WSMessage}
 */
proto.WSMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setMid(value);
      break;
    case 2:
      var value = /** @type {!proto.WSMessage.MsgType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setUid(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setTId(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setTxt(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.WSMessage} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.WSMessage.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.WSMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.WSMessage.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getMid();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = this.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = this.getUid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = this.getTId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = this.getTxt();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional int64 mid = 1;
 * @return {number}
 */
proto.WSMessage.prototype.getMid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.WSMessage.prototype.setMid = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional MsgType type = 2;
 * @return {!proto.WSMessage.MsgType}
 */
proto.WSMessage.prototype.getType = function() {
  return /** @type {!proto.WSMessage.MsgType} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.WSMessage.MsgType} value */
proto.WSMessage.prototype.setType = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string uid = 3;
 * @return {string}
 */
proto.WSMessage.prototype.getUid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.WSMessage.prototype.setUid = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string t_id = 4;
 * @return {string}
 */
proto.WSMessage.prototype.getTId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.WSMessage.prototype.setTId = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional string txt = 5;
 * @return {string}
 */
proto.WSMessage.prototype.getTxt = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.WSMessage.prototype.setTxt = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * @enum {number}
 */
proto.WSMessage.MsgType = {
  MSG: 0,
  TXT: 1,
  TIME: 2,
  REG: 3,
  GROUP: 4
};

goog.object.extend(exports, proto);
